package goldext

import (
	"strings"
)

// EmojiPreprocessor replaces emoji shortcodes with Unicode emoji characters
// but avoids processing text inside code blocks
func EmojiPreprocessor(markdown string, _ string) string {
	// Process line by line instead of relying on regex which might fail on large documents
	lines := strings.Split(markdown, "\n")
	var result []string

	inCodeBlock := false

	// Define emoji mappings
	// Data from https://gist.github.com/rxaviers/7360908
	emojis := map[string]string{
		":grinning:":                       "😀",
		":smiley:":                         "😃",
		":smile:":                          "😄",
		":grin:":                           "😁",
		":laughing:":                       "😆",
		":satisfied:":                      "😆",
		":sweat_smile:":                    "😅",
		":rofl:":                           "🤣",
		":joy:":                            "😂",
		":slightly_smiling_face:":          "🙂",
		":upside_down_face:":               "🙃",
		":wink:":                           "😉",
		":blush:":                          "😊",
		":innocent:":                       "😇",
		":smiling_face_with_three_hearts:": "🥰",
		":heart_eyes:":                     "😍",
		":star_struck:":                    "🤩",
		":kissing_heart:":                  "😘",
		":kissing:":                        "😗",
		":relaxed:":                        "☺️",
		":kissing_closed_eyes:":            "😚",
		":kissing_smiling_eyes:":           "😙",
		":yum:":                            "😋",
		":stuck_out_tongue:":               "😛",
		":stuck_out_tongue_winking_eye:":   "😜",
		":zany_face:":                      "🤪",
		":stuck_out_tongue_closed_eyes:":   "😝",
		":money_mouth_face:":               "🤑",
		":hugs:":                           "🤗",
		":hand_over_mouth:":                "🤭",
		":shushing_face:":                  "🤫",
		":thinking:":                       "🤔",
		":zipper_mouth_face:":              "🤐",
		":raised_eyebrow:":                 "🤨",
		":neutral_face:":                   "😐",
		":expressionless:":                 "😑",
		":no_mouth:":                       "😶",
		":smirk:":                          "😏",
		":unamused:":                       "😒",
		":roll_eyes:":                      "🙄",
		":grimacing:":                      "😬",
		":lying_face:":                     "🤥",
		":relieved:":                       "😌",
		":pensive:":                        "😔",
		":sleepy:":                         "😪",
		":drooling_face:":                  "🤤",
		":sleeping:":                       "😴",
		":mask:":                           "😷",
		":face_with_thermometer:":          "🤒",
		":face_with_head_bandage:":         "🤕",
		":nauseated_face:":                 "🤢",
		":vomiting_face:":                  "🤮",
		":sneezing_face:":                  "🤧",
		":hot_face:":                       "🥵",
		":cold_face:":                      "🥶",
		":woozy_face:":                     "🥴",
		":dizzy_face:":                     "😵",
		":exploding_head:":                 "🤯",
		":cowboy_hat_face:":                "🤠",
		":partying_face:":                  "🥳",
		":sunglasses:":                     "😎",
		":nerd_face:":                      "🤓",
		":monocle_face:":                   "🧐",
		":confused:":                       "😕",
		":worried:":                        "😟",
		":slightly_frowning_face:":         "🙁",
		":frowning_face:":                  "☹️",
		":open_mouth:":                     "😮",
		":hushed:":                         "😯",
		":astonished:":                     "😲",
		":flushed:":                        "😳",
		":pleading_face:":                  "🥺",
		":frowning:":                       "😦",
		":anguished:":                      "😧",
		":fearful:":                        "😨",
		":cold_sweat:":                     "😰",
		":disappointed_relieved:":          "😥",
		":cry:":                            "😢",
		":sob:":                            "😭",
		":scream:":                         "😱",
		":confounded:":                     "😖",
		":persevere:":                      "😣",
		":disappointed:":                   "😞",
		":sweat:":                          "😓",
		":weary:":                          "😩",
		":tired_face:":                     "😫",
		":yawning_face:":                   "🥱",
		":triumph:":                        "😤",
		":rage:":                           "😡",
		":pout:":                           "😡",
		":angry:":                          "😠",
		":cursing_face:":                   "🤬",
		":smiling_imp:":                    "😈",
		":imp:":                            "👿",
		":skull:":                          "💀",
		":skull_and_crossbones:":           "☠️",
		":clown_face:":                     "🤡",
		":ghost:":                          "👻",
		":alien:":                          "👽",
		":yellow_heart:":                   "💛",
		":blue_heart:":                     "💙",
		":purple_heart:":                   "💜",
		":heart:":                          "❤️",
		":green_heart:":                    "💚",
		":broken_heart:":                   "💔",
		":heartbeat:":                      "💓",
		":heartpulse:":                     "💗",
		":two_hearts:":                     "💕",
		":revolving_hearts:":               "💞",
		":cupid:":                          "💘",
		":sparkling_heart:":                "💖",
		":sparkles:":                       "✨",
		":star:":                           "⭐",
		":star2:":                          "🌟",
		":dizzy:":                          "💫",
		":boom:":                           "💥",
		":collision:":                      "💥",
		":anger:":                          "💢",
		":exclamation:":                    "❗",
		":question:":                       "❓",
		":grey_exclamation:":               "❕",
		":grey_question:":                  "❔",
		":zzz:":                            "💤",
		":dash:":                           "💨",
		":sweat_drops:":                    "💦",
		":notes:":                          "🎶",
		":musical_note:":                   "🎵",
		":fire:":                           "🔥",
		":hankey:":                         "💩",
		":poop:":                           "💩",
		":shit:":                           "💩",
		":+1:":                             "👍",
		":thumbsup:":                       "👍",
		":-1:":                             "👎",
		":thumbsdown:":                     "👎",
		":ok_hand:":                        "👌",
		":punch:":                          "👊",
		":facepunch:":                      "👊",
		":fist:":                           "✊",
		":v:":                              "✌️",
		":wave:":                           "👋",
		":hand:":                           "✋",
		":raised_hand:":                    "✋",
		":open_hands:":                     "👐",
		":point_up:":                       "☝️",
		":point_down:":                     "👇",
		":point_left:":                     "👈",
		":point_right:":                    "👉",
		":raised_hands:":                   "🙌",
		":pray:":                           "🙏",
		":point_up_2:":                     "👆",
		":clap:":                           "👏",
		":muscle:":                         "💪",
		":metal:":                          "🤘",
		":fu:":                             "🖕",
		":smiley_cat:":                     "😺",
		":smile_cat:":                      "😸",
		":heart_eyes_cat:":                 "😻",
		":kissing_cat:":                    "😽",
		":smirk_cat:":                      "😼",
		":scream_cat:":                     "🙀",
		":crying_cat_face:":                "😿",
		":joy_cat:":                        "😹",
		":pouting_cat:":                    "😾",
		":feet:":                           "👣",
		":lips:":                           "👄",
		":kiss:":                           "💋",
		":droplet:":                        "💧",
		":ear:":                            "👂",
		":eyes:":                           "👀",
		":nose:":                           "👃",
		":tongue:":                         "👅",
		":love_letter:":                    "💌",
		":bust_in_silhouette:":             "👤",
		":busts_in_silhouette:":            "👥",
		":speech_balloon:":                 "💬",
		":thought_balloon:":                "💭",
		":anger_right:":                    "🗯️",
		":sunny:":                          "☀️",
		":umbrella:":                       "☔",
		":cloud:":                          "☁️",
		":snowflake:":                      "❄️",
		":snowman:":                        "⛄",
		":zap:":                            "⚡",
		":cyclone:":                        "🌀",
		":foggy:":                          "🌁",
		":ocean:":                          "🌊",
		":cat:":                            "🐱",
		":dog:":                            "🐶",
		":mouse:":                          "🐭",
		":hamster:":                        "🐹",
		":rabbit:":                         "🐰",
		":wolf:":                           "🐺",
		":frog:":                           "🐸",
		":tiger:":                          "🐯",
		":koala:":                          "🐨",
		":bear:":                           "🐻",
		":pig:":                            "🐷",
		":pig_nose:":                       "🐽",
		":cow:":                            "🐮",
		":boar:":                           "🐗",
		":monkey_face:":                    "🐵",
		":monkey:":                         "🐒",
		":horse:":                          "🐴",
		":racehorse:":                      "🐎",
		":camel:":                          "🐫",
		":sheep:":                          "🐑",
		":elephant:":                       "🐘",
		":panda_face:":                     "🐼",
		":snake:":                          "🐍",
		":bird:":                           "🐦",
		":baby_chick:":                     "🐤",
		":hatched_chick:":                  "🐥",
		":hatching_chick:":                 "🐣",
		":chicken:":                        "🐔",
		":penguin:":                        "🐧",
		":turtle:":                         "🐢",
		":bug:":                            "🐛",
		":honeybee:":                       "🐝",
		":beetle:":                         "🐞",
		":snail:":                          "🐌",
		":octopus:":                        "🐙",
		":tropical_fish:":                  "🐠",
		":fish:":                           "🐟",
		":whale:":                          "🐳",
		":whale2:":                         "🐋",
		":dolphin:":                        "🐬",
		":cow2:":                           "🐄",
		":ram:":                            "🐏",
		":rat:":                            "🐀",
		":water_buffalo:":                  "🐃",
		":tiger2:":                         "🐅",
		":rabbit2:":                        "🐇",
		":dragon:":                         "🐉",
		":goat:":                           "🐐",
		":rooster:":                        "🐓",
		":dog2:":                           "🐕",
		":pig2:":                           "🐖",
		":mouse2:":                         "🐁",
		":ox:":                             "🐂",
		":dragon_face:":                    "🐲",
		":blowfish:":                       "🐡",
		":crocodile:":                      "🐊",
		":dromedary_camel:":                "🐪",
		":leopard:":                        "🐆",
		":cat2:":                           "🐈",
		":poodle:":                         "🐩",
		":hammer:":                         "🔨",
		":axe:":                            "🪓",
		":hammer_and_wrench:":              "🛠️",
		":bomb:":                           "💣",
		":shield:":                         "🛡️",
		":wrench:":                         "🔧",
		":gear:":                           "⚙️",
		":100:":                            "💯",
		":1234:":                           "🔢",
		":8ball:":                          "🎱",
		":a:":                              "🅰️",
		":ab:":                             "🆎",
		":abc:":                            "🔤",
		":abcd:":                           "🔡",
		":accept:":                         "🉑",
		":aerial_tramway:":                 "🚡",
		":airplane:":                       "✈️",
		":alarm_clock:":                    "⏰",
		":ambulance:":                      "🚑",
		":anchor:":                         "⚓",
		":apple:":                          "🍎",
		":aquarius:":                       "♒",
		":aries:":                          "♈",
		":arrow_backward:":                 "◀️",
		":arrow_double_down:":              "⏬",
		":arrow_double_up:":                "⏫",
		":arrow_down:":                     "⬇️",
		":arrow_down_small:":               "🔽",
		":arrow_forward:":                  "▶️",
		":arrow_heading_down:":             "⤵️",
		":arrow_heading_up:":               "⤴️",
		":arrow_left:":                     "⬅️",
		":arrow_lower_left:":               "↙️",
		":arrow_lower_right:":              "↘️",
		":arrow_right:":                    "➡️",
		":arrow_right_hook:":               "↪️",
		":arrow_up:":                       "⬆️",
		":arrow_up_down:":                  "↕️",
		":arrow_up_small:":                 "🔼",
		":arrow_upper_left:":               "↖️",
		":arrow_upper_right:":              "↗️",
		":arrows_clockwise:":               "🔃",
		":arrows_counterclockwise:":        "🔄",
		":art:":                            "🎨",
		":articulated_lorry:":              "🚛",
		":x:":                              "❌",
		":heavy_check_mark:":               "✔️",
		":heavy_multiplication_x:":         "✖️",
		":heavy_plus_sign:":                "➕",
		":heavy_minus_sign:":               "➖",
		":heavy_division_sign:":            "➗",
		":computer:":                       "💻",
		":keyboard:":                       "⌨️",
		":mouse3:":                         "🖱️",
		":trackball:":                      "🖲️",
		":joystick:":                       "🕹️",
		":gamepad:":                        "🎮",
		":one:":                            "1️⃣",
		":two:":                            "2️⃣",
		":three:":                          "3️⃣",
		":four:":                           "4️⃣",
		":five:":                           "5️⃣",
		":six:":                            "6️⃣",
		":seven:":                          "7️⃣",
		":eight:":                          "8️⃣",
		":nine:":                           "9️⃣",
		":zero:":                           "0️⃣",
		":hash:":                           "#️⃣",
		":ballot_box_with_check:":          "☑️",
		":white_check_mark:":               "✅",
		":green_square:":                   "🟩",
		":blue_square:":                    "🟦",
		":shipit:":                         "🚢",
	}

	for _, line := range lines {
		// Check if this line starts or ends a code block
		trimmedLine := strings.TrimSpace(line)
		if strings.HasPrefix(trimmedLine, "```") || strings.HasPrefix(trimmedLine, "~~~") {
			inCodeBlock = !inCodeBlock
			result = append(result, line)
			continue
		}

		// If we're in a code block, don't process
		if inCodeBlock {
			result = append(result, line)
			continue
		}

		// Process each segment of the line, preserving inline code
		var processedLine string
		segments := strings.Split(line, "`")

		for i, segment := range segments {
			// Even segments (0, 2, 4...) are outside inline code
			if i%2 == 0 {
				// Apply all replacements to non-code segments
				for shortcode, emoji := range emojis {
					segment = strings.ReplaceAll(segment, shortcode, emoji)
				}
				processedLine += segment
			} else {
				// Odd segments (1, 3, 5...) are inside inline code - preserve them
				processedLine += "`" + segment + "`"
			}
		}

		result = append(result, processedLine)
	}

	return strings.Join(result, "\n")
}
